name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Xcode project
        run: swift package generate-xcodeproj
      - name: Build
        run: xcodebuild build -sdk iphoneos -scheme 'MMMObservables-Package'
